# Generated by Django 2.2.6 on 2020-05-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Category', models.CharField(choices=[('car', 'CAR'), ('home', 'Furniture'), ('education', 'EDUCATION'), ('electronics', 'ELECTRONICS'), ('misc', 'MISC')], default='misc', max_length=5)),
                ('Price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Country', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
            ],
        ),
    ]
