# Generated by Django 2.2.6 on 2020-05-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200528_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Country',
            new_name='state',
        ),
    ]
