# Generated by Django 2.2.6 on 2020-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200528_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(default='mihir', max_length=100),
            preserve_default=False,
        ),
    ]
