# Generated by Django 2.2.6 on 2020-05-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='Carts',
        ),
    ]
