# Generated by Django 2.2.6 on 2020-05-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20200529_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='author',
            field=models.CharField(default='mihir', max_length=100),
            preserve_default=False,
        ),
    ]
