# Generated by Django 2.2.6 on 2020-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_carts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
